# Generated by Django 6.1.1 on 2026-09-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('market_region', models.CharField(choices=[('KR', '국내'), ('GLOBAL', '해외')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ko', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('set_name', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=50)),
                ('rarity', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_card_source_external_id')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('RAW', 'RAW'), ('PSA', 'PSA'), ('BGS', 'BGS'), ('CGC', 'CGC'), ('SEALED', 'SEALED'), ('UNKNOWN', 'UNKNOWN')], max_length=10)),
                ('grading_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('calculated_at', models.DateTimeField()),
                ('median_price', models.PositiveBigIntegerField()),
                ('average_price', models.PositiveBigIntegerField()),
                ('min_price', models.PositiveBigIntegerField()),
                ('max_price', models.PositiveBigIntegerField()),
                ('listing_count', models.PositiveIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_histories', to='cards.card')),
            ],
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('price', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('url', models.URLField()),
                ('condition', models.CharField(choices=[('RAW', 'RAW'), ('PSA', 'PSA'), ('BGS', 'BGS'), ('CGC', 'CGC'), ('SEALED', 'SEALED'), ('UNKNOWN', 'UNKNOWN')], max_length=10)),
                ('grading_company', models.CharField(blank=True, choices=[('PSA', 'PSA'), ('BGS', 'BGS'), ('CGC', 'CGC')], max_length=3, null=True)),
                ('grading_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('collected_at', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_listings', to='cards.card')),
                ('market_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_listings', to='cards.marketsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('market_source', 'external_id'), name='unique_listing_source_external_id')],
            },
        ),
    ]
