# Generated by Django 6.1.1 on 2026-09-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='currency',
            field=models.CharField(default='KRW', max_length=3),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='average_price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='max_price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='median_price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
