# Generated by Django 6.1.1 on 2026-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_pricehistory_currency_alter_marketlisting_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketlisting',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
